# Generated by Django 3.1.3 on 2020-11-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type_name', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('template_id', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=512)),
                ('mapping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='core.mapping')),
            ],
        ),
        migrations.CreateModel(
            name='FHIRProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=512)),
                ('mapping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.mapping')),
            ],
        ),
        migrations.CreateModel(
            name='FHIRAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type_name', models.CharField(max_length=128)),
                ('maps_to', models.ManyToManyField(related_name='mapped_from', to='core.Attribute')),
                ('parent_attribute', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fhirattribute')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.fhirprofile')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='parent_template_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.templateclass'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='type_class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.templateclass'),
        ),
    ]
