# Generated by Django 3.1.3 on 2020-11-27 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201127_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateclass',
            name='mapping',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_classes', to='core.mapping'),
        ),
    ]
