# Generated by Django 3.1.3 on 2021-01-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0003_auto_20201127_1933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribute',
            new_name='TemplateAttribute',
        ),
        migrations.RenameField(
            model_name='templateclass',
            old_name='path',
            new_name='archetyp_id',
        ),
        migrations.RemoveField(
            model_name='templateclass',
            name='template_id',
        ),
        migrations.AddField(
            model_name='mapping',
            name='template_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
