# Generated by Django 3.1.3 on 2021-03-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210321_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
